name: Deploy
on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "npm"
    cancel-in-progress: false

jobs:
    deploy:
        name: Deploy to npm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: Get tag version
              if: startsWith(github.ref, 'refs/tags/')
              id: get_tag_version
              run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
            - name: Build and test Node version
              run: deno run -A ./scripts/build_npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
            - name: Publish npm package
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: cd npm && npm publish --no-git-checks
